kind: Secret
apiVersion: v1
metadata:
  name: <NAME>
type: Opaque
stringData: # visit https://github.com/anchore/grype for more
  .grypeconfig: |-
    ignore:
      - package:
          name: spring-core
