apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: <NAME>
spec:
  outputs:
    latestImage: spec.params[?(@.name=="image-url")].value

  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      workspaces:
        - name: config
          secret:
            secretName: <CUSTOM_SCANNER_CONFIG_IN_K8S_SECRET> #$(runnable.spec.inputs.config_secret)$
      params: $(runnable.spec.inputs.params)$
      serviceAccountName: $(runnable.spec.inputs.serviceAccount)$
      taskRef:
        kind: ClusterTask
        name: <CLUSTER_TASK_NAME>
