apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  # tekton-source-pipelinerun
  name: <NAME>
spec:
  outputs:
    revision: spec.params[?(@.name=="source-revision")].value
    url: spec.params[?(@.name=="source-url")].value
  template:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      params: $(runnable.spec.inputs.tekton-params)$
      pipelineRef:
        name: $(selected.metadata.name)$ # Does not hardcode tekton pipeline name. Rather works based on selection of tags created in the pipeline itself. check testing-pipeline-template.yaml-->Runnable.spec.selector.resource section.
